apiVersion: v1
kind: Pod
metadata:
 name: username
 labels:
  app: username
spec:
 containers:
  - name: username
    image: docker.io/lokeshkumarsingh/username:firstimage
    ports:
     - containerPort: 80
